package expo.modules.androidgooglewebclient

import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition

/**
 * Reads Android `default_web_client_id` generated by the Google Services plugin
 * from gitignored `google-services.json` (`oauth_client` `client_type` 3).
 * Jest never loads this native module.
 */
class AndroidGoogleWebClientModule : Module() {
  companion object {
    // A JS reload replaces Expo module instances, but cannot change this process-wide claim.
    private var processAuthMode: String? = null

    @Synchronized
    private fun claimAuthMode(mode: String): Boolean {
      if (mode != "emulator" && mode != "cloud") return false
      val existing = processAuthMode
      if (existing != null) return existing == mode
      processAuthMode = mode
      return true
    }
  }

  override fun definition() = ModuleDefinition {
    Name("AndroidGoogleWebClient")

    Function("claimFirebaseAuthMode") { mode: String ->
      claimAuthMode(mode)
    }

    Function("getDefaultWebClientId") {
      val context = appContext.reactContext ?: return@Function null
      val resourceId =
        context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
      if (resourceId == 0) {
        return@Function null
      }
      val value = context.getString(resourceId).trim()
      if (value.isEmpty()) {
        return@Function null
      }
      value
    }
  }
}
