# Generated by Django 6.1 on 2026-08-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=36, null=True)),  # noqa: DJ001
                ("position_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_progress",
                        to="catalog.episode",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_progress",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user_profile__isnull", False)),
                        fields=("user_profile", "episode"),
                        name="progress_watchprogress_unique_user_episode",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("device_id__isnull", False)),
                        fields=("device_id", "episode"),
                        name="progress_watchprogress_unique_device_episode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("device_id__isnull", True), ("user_profile__isnull", False)),
                            models.Q(("device_id__isnull", False), ("user_profile__isnull", True)),
                            _connector="OR",
                        ),
                        name="progress_watchprogress_subject_xor",
                    ),
                ],
            },
        ),
    ]
