# Generated by Django 6.1.1 on 2026-09-20 18:16

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0002_accountdeletion_userprofile_ads_consent_and_more"),
        ("catalog", "0005_episode_access_configuration"),
        ("progress", "0001_watchprogress"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="watchprogress",
            index=models.Index(
                condition=models.Q(("device_id__isnull", False), ("user_profile__isnull", True)),
                fields=["updated_at", "id"],
                name="progress_guest_retention_idx",
            ),
        ),
    ]
