# Generated by Django 6.1 on 2026-08-24 19:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.CharField(editable=False, max_length=40, unique=True)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "editorial_rank",
                    models.IntegerField(
                        default=0, help_text="Lower values appear first on home, then public_id."
                    ),
                ),
                (
                    "original_language",
                    models.CharField(
                        default="en",
                        help_text="ISO 639-1 original language. MVP catalog language is English.",
                        max_length=2,
                    ),
                ),
                (
                    "artwork_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL or path metadata only. Do not store binary artwork here.",
                        max_length=500,
                    ),
                ),
                (
                    "age_rating",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional metadata. Anonymous catalog GET does not age-gate.",
                        max_length=16,
                    ),
                ),
                ("content_warnings", models.TextField(blank=True, default="")),
                ("attribution", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(blank=True, related_name="series", to="catalog.genre"),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ("editorial_rank", "public_id"),
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.CharField(editable=False, max_length=40, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="1-based order unique within the season."
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "window_starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional publication window start (inclusive).",
                        null=True,
                    ),
                ),
                (
                    "window_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional publication window end (exclusive). Null is open-ended.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="catalog.season",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ("season__number", "order"),
            },
        ),
        migrations.CreateModel(
            name="ContentRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "licensor",
                    models.CharField(
                        help_text="Licensor display/reference name. Use synthetic values in this repository.",
                        max_length=200,
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        help_text="Opaque private-system contract reference. Never store rates.",
                        max_length=200,
                    ),
                ),
                (
                    "territory_allowlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2),
                        help_text="ISO 3166-1 alpha-2 codes. Empty allowlists are invalid.",
                    ),
                ),
                (
                    "territory_denylist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2),
                        blank=True,
                        default=list,
                        help_text="ISO 3166-1 alpha-2 codes subtracted from the allowlist.",
                    ),
                ),
                (
                    "platforms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        help_text="Granted platforms. MVP values: ios, android.",
                    ),
                ),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2),
                        help_text="Licensed original/subtitle/dub language codes (ISO 639-1).",
                    ),
                ),
                ("starts_at", models.DateTimeField(help_text="Rights window start (inclusive).")),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rights window end (exclusive). Null means open-ended.",
                        null=True,
                    ),
                ),
                ("exclusive", models.BooleanField(default=False)),
                ("takedown", models.BooleanField(db_index=True, default=False)),
                (
                    "drm_required",
                    models.BooleanField(
                        default=False,
                        help_text="Stored for D-019; catalog GET does not enforce DRM.",
                    ),
                ),
                (
                    "revenue_share_rule_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Opaque private-system rule reference. Never store rates.",
                        max_length=200,
                    ),
                ),
                ("promotional_clip_permission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rights",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SeriesTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="ISO 639-1. English is required to publish.", max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("synopsis", models.TextField()),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ("language",),
            },
        ),
        migrations.CreateModel(
            name="EpisodeTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=200)),
                ("synopsis", models.TextField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.episode",
                    ),
                ),
            ],
            options={
                "ordering": ("language",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("episode", "language"),
                        name="catalog_episodetranslation_unique_language",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("series", "number"), name="catalog_season_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(
                fields=("season", "order"), name="catalog_episode_unique_season_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("window_ends_at__isnull", True),
                    ("window_starts_at__isnull", True),
                    ("window_starts_at__lt", models.F("window_ends_at")),
                    _connector="OR",
                ),
                name="catalog_episode_window_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentright",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__lt", models.F("ends_at")),
                    _connector="OR",
                ),
                name="catalog_contentright_window_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentright",
            constraint=models.CheckConstraint(
                condition=models.Q(("territory_allowlist__len__gt", 0)),
                name="catalog_contentright_allowlist_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentright",
            constraint=models.CheckConstraint(
                condition=models.Q(("platforms__len__gt", 0)),
                name="catalog_contentright_platforms_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentright",
            constraint=models.CheckConstraint(
                condition=models.Q(("languages__len__gt", 0)),
                name="catalog_contentright_languages_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="seriestranslation",
            constraint=models.UniqueConstraint(
                fields=("series", "language"), name="catalog_seriestranslation_unique_language"
            ),
        ),
    ]
