# Generated by Django 6.1 on 2026-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_mvp_self_owned_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentright",
            name="drm_required",
            field=models.BooleanField(
                default=False,
                help_text="DRM-required grants fail closed until a compliant provider is approved.",
            ),
        ),
        migrations.AlterField(
            model_name="contentright",
            name="promotional_clip_permission",
            field=models.BooleanField(
                default=False,
                help_text="Required before a licensed series can publish or appear in promotion.",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="promotional_use_approved",
            field=models.BooleanField(
                default=False, help_text="Confirms promotional use for self-owned material."
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="self_owned",
            field=models.BooleanField(
                default=False,
                help_text="Select the provenance path; otherwise publication requires a licensed right.",
            ),
        ),
    ]
