# Generated by Django 6.1 on 2026-09-07 17:46

import django.contrib.postgres.fields
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_restore_licensed_series_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.AddField(
            model_name="contentright",
            name="coin_access_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentright",
            name="dub_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="contentright",
            name="free_access_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentright",
            name="original_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="contentright",
            name="paid_promotion_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentright",
            name="rewarded_ad_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentright",
            name="storefronts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="contentright",
            name="subtitle_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="distribution_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                default=apps.catalog.models.default_distribution_languages,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="distribution_platforms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                default=apps.catalog.models.default_distribution_platforms,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="distribution_storefronts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                default=apps.catalog.models.default_distribution_storefronts,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="distribution_territories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                default=apps.catalog.models.default_distribution_territories,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="content_segments",
            field=models.ManyToManyField(
                blank=True, related_name="series", to="catalog.contentsegment"
            ),
        ),
    ]
