# Generated by Django 6.1 on 2026-09-07 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_launch_context_rights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialAccessRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("policy_version", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="episode",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Series defaults"),
                    ("free", "Free"),
                    ("rewarded_ad", "Rewarded ad"),
                    ("coin", "Coin"),
                    ("both", "Rewarded ad or coin"),
                ],
                default="inherit",
                db_default="inherit",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="coin_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_mode__in", ["coin", "both"]),
                        ("coin_price__gt", 0),
                        ("coin_price__isnull", False),
                    ),
                    models.Q(
                        ("access_mode__in", ["inherit", "free", "rewarded_ad"]),
                        ("coin_price__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="catalog_episode_access_price_valid",
            ),
        ),
        migrations.AddField(
            model_name="editorialaccessrevision",
            name="actor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="editorialaccessrevision",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.episode",
            ),
        ),
        migrations.AddField(
            model_name="editorialaccessrevision",
            name="series",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="catalog.series"
            ),
        ),
    ]
