# Generated by Django 6.1.1 on 2026-09-07 22:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_accounting_safeguards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinUnlockCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("episode_public_id", models.CharField(max_length=40)),
                ("policy_version", models.CharField(max_length=64)),
                ("expected_coin_price", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellations",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("wallet", "request_id"), name="wallet_cancel_unique_request"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_coin_price__gte", 1),
                            ("expected_coin_price__lte", 2147483647),
                        ),
                        name="wallet_cancel_bounded_price",
                    ),
                ],
            },
        ),
    ]
