# Generated by Django 6.1.1 on 2026-09-22 18:56

from decimal import Decimal

import django.core.validators
from django.db import migrations, models

FORWARD_SQL = """
CREATE FUNCTION commerce_guard_coin_pack() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE'
       OR NEW.product_id <> OLD.product_id
       OR NEW.base_coins <> OLD.base_coins
       OR NEW.bonus <> OLD.bonus
       OR NEW.coins <> OLD.coins
       OR NEW.starts_at IS DISTINCT FROM OLD.starts_at
       OR NEW.ends_at IS DISTINCT FROM OLD.ends_at
       OR NEW.created_at <> OLD.created_at
       OR (OLD.retired_at IS NOT NULL
           AND (NEW.is_active OR NEW.retired_at IS DISTINCT FROM OLD.retired_at))
    THEN
        RAISE EXCEPTION 'Coin pack amounts and schedule are fixed once saved'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER commerce_coin_pack_guard BEFORE UPDATE OR DELETE ON commerce_coinpack
FOR EACH ROW EXECUTE FUNCTION commerce_guard_coin_pack();
"""

REVERSE_SQL = """
DROP TRIGGER commerce_coin_pack_guard ON commerce_coinpack;
DROP FUNCTION commerce_guard_coin_pack();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_history_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Google Play in-app product ID. Its price is set in Google Play Console.",
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator("\\A[A-Za-z0-9_.:/-]+\\Z")
                        ],
                    ),
                ),
                (
                    "base_coins",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ]
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Extra coins as a fraction of base coins: 0.20 gives 20% more.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("2.00")),
                        ],
                    ),
                ),
                ("coins", models.PositiveIntegerField(editable=False)),
                ("badge", models.CharField(blank=True, max_length=24)),
                ("highlighted", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("retired_at", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("sort_order", "coins", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("coins__gte", models.F("base_coins")), ("coins__lte", 2147483647)
                        ),
                        name="commerce_pack_coins_cover_base",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("bonus__gte", 0), ("bonus__lte", Decimal("2.00"))),
                        name="commerce_pack_bonus_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("starts_at__isnull", True),
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="commerce_pack_schedule_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_active", True), ("retired_at__isnull", True)),
                            models.Q(("is_active", False), ("retired_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="commerce_pack_retirement",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
