# Generated by Django 6.1 on 2026-08-27 20:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 hex digest of the uploaded master bytes.", max_length=64
                    ),
                ),
                ("provider_name", models.CharField(max_length=32)),
                ("provider_asset_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending upload"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="pending_upload",
                        max_length=16,
                    ),
                ),
                (
                    "captions_language",
                    models.CharField(
                        default="en",
                        help_text="ISO 639-1 language of the sidecar captions.",
                        max_length=2,
                    ),
                ),
                ("has_captions", models.BooleanField(default=False)),
                ("thumbnail_count", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "renditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), blank=True, default=list
                    ),
                ),
                (
                    "diagnostic_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Safe, redacted staff diagnostic. Never keys, payloads, or signed URLs.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="catalog.episode",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["episode", "state"], name="playback_me_episode_091cce_idx"
                    ),
                    models.Index(fields=["checksum"], name="playback_me_checksu_5fd788_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ("pending_upload", "uploaded", "processing", "ready"))
                        ),
                        fields=("episode", "checksum"),
                        name="playback_mediaasset_unique_active_checksum",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ("pending_upload", "uploaded", "processing", "ready"))
                        ),
                        fields=("episode",),
                        name="playback_mediaasset_one_active_per_episode",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "ready")),
                        fields=("episode",),
                        name="playback_mediaasset_one_ready_per_episode",
                    ),
                ],
            },
        ),
    ]
