"""Write docs/api/openapi.yaml from Django with drf-spectacular.

Schema generation inspects views and serializers. It does not need a live
PostgreSQL connection. DATABASE_URL is still required because Django settings
parse it; the documented local example is a safe dummy value.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "api" / "openapi.yaml"
DEFAULT_DATABASE_URL = "postgresql://shortform@127.0.0.1:5432/shortform"
HEADER = "# Generated by `pnpm contract:generate`. Do not edit by hand.\n"


def main() -> int:
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
    os.environ.setdefault("DATABASE_URL", DEFAULT_DATABASE_URL)
    sys.path.insert(0, str(ROOT / "backend"))

    import django
    from django.core.management import call_command

    django.setup()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    call_command("spectacular", file=str(OUTPUT), validate=True)
    body = OUTPUT.read_text(encoding="utf-8")
    if body.startswith(HEADER):
        body = body[len(HEADER) :]
    OUTPUT.write_text(HEADER + body.replace("\r\n", "\n"), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
