# Generated by Django 6.1 on 2026-08-31 07:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.advertising.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_accountdeletion_userprofile_ads_consent_and_more"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("request_id", models.UUIDField()),
                (
                    "custom_data",
                    models.CharField(
                        default=apps.advertising.models.opaque_binding, max_length=64, unique=True
                    ),
                ),
                (
                    "ssv_user_id",
                    models.CharField(default=apps.advertising.models.opaque_binding, max_length=64),
                ),
                ("territory", models.CharField(max_length=2)),
                ("platform", models.CharField(max_length=7)),
                ("language", models.CharField(max_length=2)),
                ("ad_unit_id", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("provider_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.episode"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.userprofile"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_profile", "request_id"), name="reward_request_unique"
                    )
                ],
            },
        ),
    ]
