# Generated by Django 6.1 on 2026-08-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("staff", "Staff"), ("rewarded_ad", "Rewarded ad")],
                        default="staff",
                        max_length=32,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="catalog.episode",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_entitlements",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-granted_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_profile", "episode"),
                        name="entitlements_episodeentitlement_unique_profile_episode",
                    )
                ],
            },
        ),
    ]
