# Generated by Django 6.1 on 2026-08-28 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("entitlements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "free_episode_order_max",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="1-based max Episode.order treated as free per season. Series-wide rows only.",
                    ),
                ),
                ("rewarded_ad_enabled", models.BooleanField(default=True)),
                (
                    "force_free",
                    models.BooleanField(
                        default=False,
                        help_text="Episode override only: treat as free regardless of order.",
                    ),
                ),
                (
                    "force_lock",
                    models.BooleanField(
                        default=False,
                        help_text="Episode override only: skip the free window (entitlement still grants).",
                    ),
                ),
                ("coin_unlock_enabled", models.BooleanField(default=False)),
                ("subscription_unlock_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty = series-wide policy. Set = episode override.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policies",
                        to="catalog.episode",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policies",
                        to="catalog.series",
                    ),
                ),
            ],
            options={
                "ordering": ("series_id", "episode_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="AccessPolicyRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("free_episode_order_max", models.PositiveIntegerField()),
                ("rewarded_ad_enabled", models.BooleanField()),
                ("force_free", models.BooleanField()),
                ("force_lock", models.BooleanField()),
                ("coin_unlock_enabled", models.BooleanField()),
                ("subscription_unlock_enabled", models.BooleanField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_policy_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.episode",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="entitlements.accesspolicy",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.series"
                    ),
                ),
            ],
            options={
                "ordering": ("-changed_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("episode__isnull", True)),
                fields=("series",),
                name="entitlements_accesspolicy_unique_series_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("episode__isnull", False)),
                fields=("episode",),
                name="entitlements_accesspolicy_unique_episode",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("coin_unlock_enabled", False)),
                name="entitlements_accesspolicy_coins_disabled_mvp",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("subscription_unlock_enabled", False)),
                name="entitlements_accesspolicy_subscription_disabled_mvp",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("force_free", True), ("force_lock", True), _negated=True),
                name="entitlements_accesspolicy_not_force_free_and_lock",
            ),
        ),
    ]
