# Generated by Django 6.1 on 2026-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("entitlements", "0002_accesspolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspolicy",
            name="free_episode_order_max",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Series-wide: 1-based max Episode.order treated as free per season. Ignored on episode override rows; the series-level value (or D-006 default) applies.",
            ),
        ),
        migrations.AlterField(
            model_name="accesspolicy",
            name="rewarded_ad_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Series-wide: whether rewarded-ad offers may appear. Ignored on episode override rows; the series-level value (or D-006 default) applies.",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesspolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("episode__isnull", False),
                    models.Q(("force_free", False), ("force_lock", False)),
                    _connector="OR",
                ),
                name="entitlements_accesspolicy_series_level_no_force_flags",
            ),
        ),
    ]
