# Generated by Django 6.1.1 on 2026-09-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entitlements", "0003_accesspolicy_series_level_no_force_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodeentitlement",
            name="source",
            field=models.CharField(
                choices=[("staff", "Staff"), ("rewarded_ad", "Rewarded ad"), ("coin", "Coin")],
                default="staff",
                max_length=32,
            ),
        ),
    ]
